In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import quantstats as qs

In [2]:
df_rub = pd.read_csv('rubber.csv')

In [3]:
df_rub = df_rub.set_index(pd.to_datetime(df_rub['Date'],format='%d%B %Y'))
del df_rub['Date']
df_rub

             USS3   RSS3  Filed Latex  Cup Lump
Date
2021-01-05  57.00  59.93         50.0     38.10
2021-01-06  58.16  60.59         51.0     38.50
2021-01-07  57.70  61.72         52.0     38.65
2021-01-08  58.59  62.39         52.5     39.45
2021-01-12  56.10  59.21         52.0     38.30
2021-01-13  57.26  59.89         51.5     38.30
2021-01-14  57.19  59.74         51.0     38.80
2021-01-15  56.62  61.52         51.0     39.00
2021-01-18  57.52  61.08         49.0     39.50
2021-01-19  56.80  60.83         48.5     39.50
2021-01-20  56.40  60.29         48.0     39.70
2021-01-21  56.40  59.35         47.0     39.50
2021-01-22  55.55  57.85         46.0     39.50
2021-01-25  53.59  55.39         42.0     38.80
2021-01-26  52.60  55.68         42.0     38.15

In [4]:
df_rub.index = df_rub.index.strftime('%d.%m.%Y')

In [5]:
df_rub

             USS3   RSS3  Filed Latex  Cup Lump
Date
05.01.2021  57.00  59.93         50.0     38.10
06.01.2021  58.16  60.59         51.0     38.50
07.01.2021  57.70  61.72         52.0     38.65
08.01.2021  58.59  62.39         52.5     39.45
12.01.2021  56.10  59.21         52.0     38.30
13.01.2021  57.26  59.89         51.5     38.30
14.01.2021  57.19  59.74         51.0     38.80
15.01.2021  56.62  61.52         51.0     39.00
18.01.2021  57.52  61.08         49.0     39.50
19.01.2021  56.80  60.83         48.5     39.50
20.01.2021  56.40  60.29         48.0     39.70
21.01.2021  56.40  59.35         47.0     39.50
22.01.2021  55.55  57.85         46.0     39.50
25.01.2021  53.59  55.39         42.0     38.80
26.01.2021  52.60  55.68         42.0     38.15

In [6]:
df_rub.to_csv('df_rub.csv')